projects:
  - canary
  - customizable-canary
  - kobenhavn
  - albertslund
  - aalborg
  - aarhus
  - ballerup
  - herning
  - odense
  - roskilde
  - silkeborg
  - sonderborg
  - sydslesvig
  - taarnby
