{{- if ne .Values.target "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy-pass
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy-pass
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy-pass
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum }}
        checksum/version: {{ .Chart.Version | toYaml | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx-proxy-pass
        image: docker.io/nginx:1.29.4-alpine
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          requests:
            memory: 128Mi
            cpu: 15m
          limits:
            memory: 128Mi
            cpu: 15m
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-proxy-pass
          items:
          - key: default.conf
            path: default.conf
          - key: index.html
            path: index.html
      nodeSelector:
        noderole.dplplatform: prod
      tolerations:
      - key: noderole.dplplatform
        operator: Equal
        value: prod
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-proxy-pass
            topologyKey: "kubernetes.io/hostname"
{{- end }}
