{{- if ne .Values.target "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy-pass
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy-pass
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy-pass
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum }}
    spec:
      containers:
      - name: nginx-proxy-pass
        image: docker.io/nginx:1.27.4-alpine
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      tolerations:
        - key: noderole.dplplatform
          operator: Equal
          value: prod
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: noderole.dplplatform
                  operator: In
                  values:
                   - prod
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-proxy-pass
          items:
          - key: default.conf
            path: default.conf
          - key: index.html
            path: index.html
{{- end }}
