apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go.{{ .Values.host }}
  annotations:
    cert-manager.io/cluster-issuer: zerossl-production
    fastly.amazee.io/watch: 'false'
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/tls-acme: 'true'
    lagoon.sh/branch: main
    lagoon.sh/version: 24.5.1
    monitor.stakater.com/enabled: 'false'
    monitor.stakater.com/overridePath: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/denylist-source-range: 95.111.211.210/32
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
spec:
  ingressClassName: nginx
  rules:
    - host:  >
        {{- if contains "www." .Values.host -}}
        {{ .Values.host | replace "www." "www.go." 1 }}
        {{- else -}}
        go.{{ .Values.host }}
        {{- end -}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if eq .Values.target "internal" }}
              service:
                name: node
                port:
                  name: http
              {{- else }}
              service:
                name: {{ .Release.Name }}-proxy-pass-go
                port:
                  number: 80
              {{- end }}
  tls:
    - hosts:
        - go.{{ .Values.host }}
      secretName: go.{{ .Values.host }}-tls
