apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.host }}
  annotations:
    cert-manager.io/cluster-issuer: zerossl-production
    fastly.amazee.io/watch: 'false'
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/tls-acme: 'true'
    lagoon.sh/branch: main
    lagoon.sh/version: 24.5.1
    monitor.stakater.com/enabled: 'false'
    monitor.stakater.com/overridePath: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if eq .Values.target "internal" }}
              service:
                name: varnish
                port:
                  name: http
              {{- else }}
              service:
                name: {{ .Release.Name }}-proxy-pass-varnish
                port:
                  number: 80
              {{- end }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
