apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-pass
spec:
  selector:
    app: {{ .Release.Name }}-proxy-pass
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
