{{- if ne .Values.target "internal" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-pass-go
spec:
  selector:
    app: {{ .Release.Name }}-proxy-pass-go
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
{{- end }}
