apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-pass-varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy-pass-varnish
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy-pass-varnish
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum }}
        checksum/version: {{ .Chart.Version | toYaml | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/varnish-configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: noderole.dplplatform
                operator: In
                values:
                - prod
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      - name: lagoon-private-registry-0-secret
      containers:
      - envFrom:
        - configMapRef:
            name: lagoon-env
        image: harbor.lagoon.dplplat01.dpl.reload.dk/{{ trimSuffix "-main" .Release.Namespace }}/main/varnish
        name: proxy-pass-varnish
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: http
          failureThreshold: 30
          periodSeconds: 1
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 3000Mi
        volumeMounts:
        - name: config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      tolerations:
      - effect: NoSchedule
        key: noderole.dplplatform
        operator: Equal
        value: prod
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-proxy-pass-varnish
          items:
          - key: default.vcl
            path: default.vcl
