apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-pass-varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-pass-varnish
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy-pass-varnish
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: noderole.dplplatform
                operator: In
                values:
                - prod
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      - name: lagoon-private-registry-0-secret
      containers:
      - envFrom:
        - configMapRef:
            name: lagoon-env
        image: harbor.lagoon.dplplat01.dpl.reload.dk/canary/main/varnish@sha256:349957461b1696999651c03217832ef52e36fa70ba401889bdce3d3bb1b5c406
        name: proxy-pass-varnish
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 3000Mi
        volumeMounts:
        - name: config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      tolerations:
      - effect: NoSchedule
        key: noderole.dplplatform
        operator: Equal
        value: prod
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-proxy-pass-varnish
          items:
          - key: default.vcl
            path: default.vcl
