apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-pass-varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-pass-varnish
  template:
    metadata:
      labels:
        app: proxy-pass-varnish
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: noderole.dplplatform
                operator: In
                values:
                - prod
      containers:
      - envFrom:
        - configMapRef:
            name: lagoon-env
        image: varnish:7.7.3-alpine
        name: proxy-pass-varnish
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 3000Mi
        volumeMounts:
        - name: config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      securityContext:
        fsGroup: 10001
        runAsGroup: 0
        runAsUser: 10000
      tolerations:
      - effect: NoSchedule
        key: noderole.dplplatform
        operator: Equal
        value: prod
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-proxy-pass-varnish
          items:
          - key: default.vcl
