{{- range $.Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  project: {{ .project }}
  source:
    repoURL: https://github.com/danskernesdigitalebibliotek/dpl-platform.git
    path: gitops/dplplat02/{{ .path | default .name }}
    targetRevision: HEAD
    helm:
      {{- if .releaseName }}
      releaseName: {{ .releaseName }}
      {{- end }}
      {{- if .valueFiles }}
      valueFiles: {{ .valueFiles | toYaml | nindent 8}}
      {{-  end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    {{- if .automated }}
    automated: {}
    {{- end }}
    syncOptions:
      - CreateNamespace=true
    {{- range .syncOptions }}
      - {{ . }}
    {{- end }}
{{- end }}
