apps:
  - name: argo-cd-resources
    project: argo-cd
    namespace: argo-cd
    automated: true

  - name: argo-cd
    project: argo-cd
    namespace: argo-cd
    automated: true

  - name: sealed-secrets
    project: sealed-secrets
    namespace: kube-system
    automated: true

  - name: vertical-pod-autoscaler
    project: vertical-pod-autoscaler
    namespace: vpa
    automated: true

  - name: ingress-nginx
    project: ingress-nginx
    namespace: ingress-nginx
    automated: true

  - name: cert-manager
    project: cert-manager
    namespace: cert-manager
    automated: false

  - name: grafana
    project: monitoring
    namespace: grafana
    automated: false

  - name: loki
    project: monitoring
    namespace: loki
    automated: true
    syncOptions:
      - ServerSideApply=true

  - name: promstack
    project: monitoring
    namespace: prometheus
    automated: true
    syncOptions:
      - ServerSideApply=true

  # Support workloads
  - name: harbor
    project: harbor
    namespace: harbor
    automated: false

  - name: moduletest-reset
    project: moduletest-reset
    namespace: moduletest-reset
    automated: false

  # Databases
  - name: mariadb-10-6-22-production-1
    project: databases
    namespace: mariadb-10-6-22-production-1
    automated: false

  - name: mariadb-10-6-22-tmp-test-1
    project: databases
    namespace: mariadb-10-6-22-tmp-test-1
    automated: false

  - name: mariadb-servers
    project: databases
    namespace: mariadb-10-06-01-test
    automated: false

automateSites: true

sites:
  - name: canary-main
    values:
      proxy-pass-service:
        host: bibliotest.deranged.dk
        target: external

  - name: canary-moduletest

  - name: aabenraa-main
    automated: true
    values:
      proxy-pass-service:
        host: www.aabenraabib.dk
        target: internal

  - name: aalborg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.aalborgbibliotekerne.dk
        target: internal

  - name: aalborg-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: aarhus-main
    automated: true
    values:
      proxy-pass-service:
        host: www.aakb.dk
        target: internal

  - name: aarhus-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: aero-main
    automated: true
    values:
      proxy-pass-service:
        host: www.arrebib.dk
        target: internal

  - name: albertslund-main
    automated: true
    values:
      proxy-pass-service:
        host: albertslundbibliotek.dk
        target: external

  - name: albertslund-moduletest

  - name: allerod-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bibliotek.alleroed.dk
        target: internal

  - name: assens-main
    automated: true
    values:
      proxy-pass-service:
        host: www.assensbib.dk
        target: external

  - name: ballerup-main
    automated: true
    values:
      proxy-pass-service:
        host: bib.ballerup.dk
        target: external

  - name: ballerup-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: billund-main
    automated: true
    values:
      proxy-pass-service:
        host: billundbib.dk
        target: external

  - name: bornholm-main
    automated: true
    values:
      proxy-pass-service:
        host: bibliotek.brk.dk
        target: external

  - name: brondby-main
    automated: true
    values:
      proxy-pass-service:
        host: www.brondby-bibliotekerne.dk
        target: internal

  - name: bronderslev-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bronderslevbib.dk
        target: internal

  - name: dragor-main
    automated: true
    values:
      proxy-pass-service:
        host: www.drabib.dk
        target: internal

  - name: egedal-main
    automated: true
    values:
      proxy-pass-service:
        host: egedalbibliotekerne.dk
        target: internal

  - name: esbjerg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.esbjergbibliotek.dk
        target: internal

  - name: faaborg-midtfyn-main
    automated: true
    values:
      proxy-pass-service:
        host: fmbib.dk
        target: internal

  - name: favrskov-main
    automated: true
    values:
      proxy-pass-service:
        host: favrskovbib.dk
        target: internal

  - name: fredensborg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.fredensborgbibliotekerne.dk
        target: internal

  - name: fredericia-main
    automated: true
    values:
      proxy-pass-service:
        host: fredericiabib.dk
        target: internal

  - name: frederiksberg-main
    automated: true
    values:
      proxy-pass-service:
        host: fkb.dk
        target: external

  - name: frederikssund-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bibliotekerne.frederikssund.dk
        target: internal

  - name: faxe-main
    automated: true
    values:
      proxy-pass-service:
        host: www.faxebibliotek.dk
        target: internal

  - name: fureso-main
    automated: true
    values:
      proxy-pass-service:
        host: furbib.dk
        target: internal

  - name: gentofte-main
    automated: true
    values:
      proxy-pass-service:
        host: genbib.dk
        target: internal

  - name: gladsaxe-main
    automated: true
    values:
      proxy-pass-service:
        host: gladbib.dk
        target: internal

  - name: glostrup-main
    automated: true
    values:
      proxy-pass-service:
        host: www.glostrupbib.dk
        target: internal

  - name: greve-main
    automated: true
    values:
      proxy-pass-service:
        host: www.grevebibliotek.dk
        target: internal

  - name: gribskov-main
    automated: true
    values:
      proxy-pass-service:
        host: www.gribskovbib.dk
        target: internal

  - name: guldborgsund-main
    automated: true
    values:
      proxy-pass-service:
        host: guldbib.dk
        target: internal

  - name: halsnaes-main
    automated: true
    values:
      proxy-pass-service:
        host: bibliotekerne.halsnaes.dk
        target: internal

  - name: haderslev-main
    automated: true
    values:
      proxy-pass-service:
        host: haderslevbibliotekerne.dk
        target: internal

  - name: hedensted-main
    automated: true
    values:
      proxy-pass-service:
        host: hedenstedbib.dk
        target: internal

  - name: helsingor-main
    automated: true
    values:
      proxy-pass-service:
        host: helsbib.dk
        target: internal

  - name: herlev-main
    automated: true
    values:
      proxy-pass-service:
        host: www.herlevbibliotek.dk
        target: internal

  - name: herning-main
    automated: true
    values:
      proxy-pass-service:
        host: www.herningbib.dk
        target: internal

  - name: herning-moduletest

  - name: hillerod-main
    automated: true
    values:
      proxy-pass-service:
        host: hilbib.dk
        target: internal

  - name: hjorring-main
    automated: true
    values:
      proxy-pass-service:
        host: hjbib.dk
        target: internal

  - name: holbaek-main
    automated: true
    values:
      proxy-pass-service:
        host: bibliotek.holbaek.dk
        target: internal

  - name: holstebro-main
    automated: true
    values:
      proxy-pass-service:
        host: www.holstebrobibliotek.dk
        target: internal

  - name: horsens-main
    automated: true
    values:
      proxy-pass-service:
        host: horsensbibliotek.dk
        target: internal

  - name: hoje-taastrup-main
    automated: true
    values:
      proxy-pass-service:
        host: bibliotek.htk.dk
        target: internal

  - name: horsholm-main
    automated: true
    values:
      proxy-pass-service:
        host: biblioteket.horsholm.dk
        target: internal

  - name: hvidovre-main
    automated: true
    values:
      proxy-pass-service:
        host: www.hvidovrebib.dk
        target: internal

  - name: ikast-brande-main
    automated: true
    values:
      proxy-pass-service:
        host: www.ikast-brandebibliotek.dk
        target: internal

  - name: ishoj-main
    automated: true
    values:
      proxy-pass-service:
        host: www.ishojbib.dk
        target: internal

  - name: kalundborg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.kalundborgbib.dk
        target: internal

  - name: kerteminde-main
    automated: true
    values:
      proxy-pass-service:
        host: kertemindebibliotekerne.dk
        target: internal

  - name: kobenhavn-main
    automated: true
    values:
      proxy-pass-service:
        host: bibliotek.kk.dk
        target: internal

  - name: kobenhavn-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: koge-main
    automated: true
    values:
      proxy-pass-service:
        host: www.koegebib.dk
        target: internal

  - name: kolding-main
    automated: true
    values:
      proxy-pass-service:
        host: koldingbib.dk
        target: external

  - name: langeland-main
    automated: true
    values:
      proxy-pass-service:
        host: langelandbibliotek.dk
        target: internal

  - name: lejre-main
    automated: true
    values:
      proxy-pass-service:
        host: lejrebib.dk
        target: internal

  - name: lolland-main
    automated: true
    values:
      proxy-pass-service:
        host: lollandbib.dk
        target: internal

  - name: lyngby-taarbaek-main
    automated: true
    values:
      proxy-pass-service:
        host: www.lyngbybib.dk
        target: internal

  - name: mariagerfjord-main
    automated: true
    values:
      proxy-pass-service:
        host: mfbib.dk
        target: internal

  - name: middelfart-main
    automated: true
    values:
      proxy-pass-service:
        host: www.middelfartbibliotek.dk
        target: internal

  - name: morso-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bibliotekmorsoe.dk
        target: internal

  - name: naestved-main
    automated: true
    values:
      proxy-pass-service:
        host: www.naesbib.dk
        target: internal

  - name: norddjurs-main
    automated: true
    values:
      proxy-pass-service:
        host: norddjursbib.dk
        target: internal

  - name: nordfyn-main
    automated: true
    values:
      proxy-pass-service:
        host: www.nordfynsbib.dk
        target: external

  - name: nyborg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.nyborgbibliotek.dk
        target: internal

  - name: odder-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bibliotek.odder.dk
        target: internal

  - name: odense-main
    automated: true
    values:
      proxy-pass-service:
        host: www.odensebib.dk
        target: internal

  - name: odense-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: odsherred-main
    automated: true
    values:
      proxy-pass-service:
        host: odsbib.dk
        target: internal

  - name: randers-main
    automated: true
    values:
      proxy-pass-service:
        host: www.randersbib.dk
        target: internal

  - name: rebild-main
    automated: true
    values:
      proxy-pass-service:
        host: www.rebildbib.dk
        target: internal

  - name: ringkobing-skjern-main
    automated: true
    values:
      proxy-pass-service:
        host: riskbib.dk
        target: internal

  - name: ringsted-main
    automated: true
    values:
      proxy-pass-service:
        host: ringstedbib.dk
        target: internal

  - name: roskilde-main
    automated: true
    values:
      proxy-pass-service:
        host: www.roskildebib.dk
        target: internal

  - name: roskilde-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: rudersdal-main
    automated: true
    values:
      proxy-pass-service:
        host: rudbib.dk
        target: internal

  - name: rodovre-main
    automated: true
    values:
      proxy-pass-service:
        host: www.rdb.dk
        target: internal

  - name: samso-main
    automated: true
    values:
      proxy-pass-service:
        host: bibliotek.samsoe.dk
        target: internal

  - name: silkeborg-main
    automated: true
    values:
      proxy-pass-service:
        host: silkeborgbib.dk
        target: internal

  - name: silkeborg-moduletest

  - name: skanderborg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bibliotek.skanderborg.dk
        target: internal

  - name: skive-main
    automated: true
    values:
      proxy-pass-service:
        host: www.skivebibliotek.dk
        target: internal

  - name: soro-main
    automated: true
    values:
      proxy-pass-service:
        host: www.soroebib.dk
        target: internal

  - name: stevns-main
    automated: true
    values:
      proxy-pass-service:
        host: www.stevnsbib.dk
        target: internal

  - name: struer-main
    automated: true
    values:
      proxy-pass-service:
        host: www.struerbibliotek.dk
        target: internal

  - name: svendborg-main
    automated: true
    values:
      proxy-pass-service:
        host: svendborgbibliotek.dk
        target: internal

  - name: syddjurs-main
    automated: true
    values:
      proxy-pass-service:
        host: syddjursbibliotek.dk
        target: internal

  - name: taarnby-main
    automated: true
    values:
      proxy-pass-service:
        host: taarnbybib.dk
        target: internal

  - name: taarnby-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: vallensbaek-main
    automated: true
    values:
      proxy-pass-service:
        host: kulturogborgerhus.vallensbaek.dk
        target: internal

  - name: varde-main
    automated: true
    values:
      proxy-pass-service:
        host: www.vardebib.dk
        target: internal

  - name: vejen-main
    automated: true
    values:
      proxy-pass-service:
        host: vejbib.dk
        target: internal

  - name: vejle-main
    automated: true
    values:
      proxy-pass-service:
        host: vejlebib.dk
        target: internal

  - name: vesthimmerland-main
    automated: true
    values:
      proxy-pass-service:
        host: www.vhbib.dk
        target: internal

  - name: viborg-main
    automated: true
    values:
      proxy-pass-service:
        host: viborgbib.dk
        target: internal

  - name: vordingborg-main
    automated: true
    values:
      proxy-pass-service:
        host: www.vordingborgbibliotekerne.dk
        target: internal

  - name: laeso-main
    automated: true
    values:
      proxy-pass-service:
        host: biblioteket.laesoe.dk
        target: internal

  - name: torshavn-main
    automated: true
    values:
      proxy-pass-service:
        host: www.bbs.fo
        target: internal

  - name: frederikshavn-main
    automated: true
    values:
      proxy-pass-service:
        host: bibl.frederikshavn.dk
        target: internal

  - name: bnf-main
    automated: true
    values:
      proxy-pass-service:
        host: delingstjenesten.dk
        target: internal

  - name: bnf-moduletest

  - name: cms-school-main
    automated: true
    values:
      proxy-pass-service:
        host: cms-school.dplplat01.dpl.reload.dk
        target: external

  - name: cms-school-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: solrod2-main
    automated: true
    values:
      proxy-pass-service:
        host: solbib.dk
        target: external

  - name: sonderborg-main
    automated: true
    values:
      proxy-pass-service:
        host: biblioteket.sonderborg.dk
        target: external

  - name: sonderborg-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: sydslesvig-main
    automated: true
    values:
      proxy-pass-service:
        host: www.dcbib.dk
        target: internal

  - name: sydslesvig-moduletest
    values:
      autoscalers:
        node:
          enabled: false

  - name: thisted-main
    automated: true
    values:
      proxy-pass-service:
        host: bib.kulturrummet.dk
        target: external
