apps:
  - name: argo-cd
    project: argo-cd
    namespace: argo-cd
    automated: true

  - name: argo-cd-resources
    project: argo-cd
    namespace: argo-cd
    automated: true

  - name: sealed-secrets
    project: sealed-secrets
    namespace: kube-system
    automated: true

  - name: ingress-nginx
    project: ingress-nginx
    namespace: ingress-nginx
    automated: true

  - name: cert-manager
    project: cert-manager
    namespace: cert-manager
    automated: true

  - name: harbor
    project: harbor
    namespace: harbor
    automated: false

  - name: loki
    project: monitoring
    namespace: loki
    automated: true
    syncOptions:
      - ServerSideApply=true

  - name: minio
    project: minio
    namespace: minio
    automated: false

  - name: mariadb-operator
    project: databases
    namespace: mariadb-operator
    automated: false

  - name: mariadb-operator-crds
    project: crds
    namespace: mariadb-operator-crds
    automated: false

  - name: mariadb-development-v10-06-22
    project: databases
    namespace: mariadb-development-v10-06-22
    automated: false
