apps:
  - name: argo-cd
    project: argo-cd
    namespace: argo-cd
    automated: true

  - name: argo-cd-resources
    project: argo-cd
    namespace: argo-cd
    automated: true

  - name: sealed-secrets
    project: sealed-secrets
    namespace: kube-system
    automated: true

  - name: ingress-nginx
    project: ingress-nginx
    namespace: ingress-nginx
    automated: true

  - name: cert-manager
    project: cert-manager
    namespace: cert-manager
    automated: true

  - name: harbor
    project: harbor
    namespace: harbor
    automated: false

  - name: loki
    project: monitoring
    namespace: loki
    automated: true
    syncOptions:
      - ServerSideApply=true

  - name: minio
    project: minio
    namespace: minio
    automated: false

  - name: mariadb-operator
    project: operators
    namespace: mariadb-operator
    automated: false

  - name: mariadb-operator-crds
    project: crds
    automated: false

  - name: mariadb-10-06-01-test
    project: databases
    namespace: mariadb-10-06-01-test
    automated: false

  - name: mariadb-10-6-22-production-1
    project: databases
    namespace: mariadb-10-6-22-production-1
    automated: false

  - name: lagoon-auxiliary
    project: lagoon-auxiliary
    namespace: lagoon-auxiliary
    automated: false

  - name: k8up
    project: k8up
    namespace: k8up
    automated: false

  - name: vertical-pod-autoscaler
    project: vertical-pod-autoscaler
    namespace: vpa
    automated: true

automateSites: true

sites:
  - name: canary-main
    namespace: canary-main
