apiVersion: v1
kind: ConfigMap
metadata:
  name: k8up-configs
data:
  global-s3-bucket:
  global-s3-endpoint:
  global-keep-jobs:
  global-stats-url:
  backof-limit:
  k8up-configs:
  global-restore-s3-endpoint:
