apiVersion: v1
kind: ConfigMap
metadata:
  name: k8up-configs
data:
  global-s3-bucket: backup
  global-s3-endpoint:
  global-keep-jobs: 1
  global-stats-url:
  backof-limit: 2
  global-restore-s3-endpoint: restore
