apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  updatePolicy:
    updateMode: InPlaceOrRecreate
  resourcePolicy:
    containerPolicies:
    - containerName: nginx
      # these are identical since we use the hpa for scaling
      minAllowed:
        cpu: 500m
        memory: 100Mi
      maxAllowed:
        cpu: 500m
        memory: 100Mi
    - containerName: php
      # these are identical since we use the hpa for scaling
      minAllowed:
        cpu: 500m
        memory: 500Mi
      maxAllowed:
        cpu: 500m
        memory: 500Mi
