apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  updatePolicy:
    updateMode: Recreate
  resourcePolicy:
    containerPolicies:
    - containerName: nginx
      minAllowed:
        cpu: 20m
        memory: 20Mi
      maxAllowed:
        cpu: 500m
        memory: 400Mi
    - containerName: php
      minAllowed:
        cpu: 20m
        memory: 20Mi
      maxAllowed:
        cpu: 1000m
        memory: 800Mi
