{{- if .Values.node.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: node-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node
  updatePolicy:
    updateMode: InPlaceOrRecreate
  resourcePolicy:
    containerPolicies:
    - containerName: node
      # these are identical since we use the hpa for scaling
      minAllowed:
        cpu: 500m
        memory: 800Mi
      maxAllowed:
        cpu: 500m
        memory: 800Mi
{{- end }}
