apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  updatePolicy:
    updateMode: Recreate
  resourcePolicy:
    containerPolicies:
    - containerName: redis
      minAllowed:
        cpu: 10m
        memory: 10Mi
      maxAllowed:
        cpu: 800m
        memory: 1000Mi
