apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: varnish-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: varnish
  updatePolicy:
    updateMode: Initial
  resourcePolicy:
    containerPolicies:
    - containerName: varnish
      minAllowed:
        cpu: 10m
        memory: 20Mi
      maxAllowed:
        cpu: 800m
        memory: 2Gi
