---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: horsholm-main
spec:
  encryptedData:
    url: AgA5FWsmj1mMvofte9Oqs8D2XVLwJNDB45cGFEyCaCV2Ev3sSyO67ygEhDyzzYk5qep9UJhn9IW0n/aVCmmZLbKSV1Zy0W7F0nJswtBPQyRz5/Dp03tmHNyoXkjQDQzD9rbccllMaOZnYVSOQXK17WbBri3hNI7+dG+iYCR7EJ8P7LH/1lbRNERqKEkdndsoMD4SYPE1VFJnvZ3vcODkOcU0NZ+VNAsIV86gesEjDBSNpX5X3q+ZtZXrFdWtEI8g1i6AHUrwb38M30IfW+uWdbvgH4azAOMAhhftkaGqmQYnNZ08b+vOSPGAoNiCbcvjAQQcWF+7arvoQ5XIbkJKK2cfJIyYz6PQeWeK/txl9/Xai+ba+BSfWTJVubWQCqHiI+HhiOWv5l7Wit+fUp01wko6FN/XOtnyJxTBU9LCB2qWva8AvAsWbWOyTgFEdsCiEw4HxQ4uHVGrw6pbkq3smAJdT4Z4gVqwf+8MYEDWPInJCQTYNY7DQPQorEdKNWVKQJiZuq9F3Cgaqw3DH6sRaR/wnjt+MIXA0vf3SmD8byzKjlNRGnn5WJ//vxC5M+nAJnIZxG1y42gqoCd5dYffbAkgCdsQc7yUaf3BwaeBiSiWJuivo9YfqhRQ0acgi0nDlpGMcKKRGq4BpjIlmpyu0byqnvlgPDtQl1V+ZAePPr4hudj04t2btJuQfzouquDDtD/VYpE9unh8PAz2+IGcXx4/HxWnAegXdYrfIE9e1Op/MYQyDiqsMMH9gOp+kQjkZR1Mf/upFcGZa4zHrHxgx7fyPsaulE0OwEwIUtH8SNssbBtmdZ6wShcZGgVnears7e/s/d+7JTNAh8Xm1Q==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: horsholm-main
